removed provides from the libmfu variants
daos-stack/mpifileutils-pkg pull request #3
Opened 2020-11-06 01:18 UTC by daltonbohning

Quick hack/fix

It doesn't seem that the lbmfu variants are
installed properly on leap15.

Modeling after hdf5-vol-daos, etc., I removed
the provides from the libmfu variants.

Perhaps the root of the problem is that
%files towards the end doesn't install the libmfu
variants utilities in the correct location?

Signed-off-by: Dalton Bohning <daltonx.bohning@intel.com>

2020-11-06 02:14 UTC, daltonbohning commented
@brianjmurrell 
The leap 15 tests are failing, as seen here:
https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-3802/2/tests
For example, datamover/copy_procs.py.
They are failing to find "dcp".
(Note - some of the tests fail for different reasons that I have since fixed.)

In this PR, I was trying to model after hdf5-vol-daos and some others, which don't seem to use the lib* variants.
For example, from the Post Restore script:
```
[2020-11-05T19:19:07.179Z] The following 70 NEW packages are going to be installed:
[2020-11-05T19:19:07.179Z]   daos daos-client daos-server daos-tests desktop-file-utils dpdk dpdk-kmp-default fio 
fuse3 hdf5-mpich hdf5-mpich-tests hdf5-openmpi3 hdf5-openmpi3-tests hdf5-vol-daos-mpich hdf5-vol-daos-mpich-tests 
hdf5-vol-daos-openmpi3 hdf5-vol-daos-openmpi3-tests hwloc hwloc-data ior-hpc json-cwx lbzip2 libabt0 libcircle2 
libdtcmp0-mpich libfabric libgfapi0 libgfrpc0 libgfxdr0 libglusterfs0 libhwloc15 libisal2 libisal_crypto2 liblttng-ust0
 liblwgrp0-mpich libmfu0-mpich libpciaccess0 libpmem1 libpmemblk1 libpmemobj1 libprotobuf20 libprotobuf-c1
 libprotobuf-c-devel libprotoc20 librados2 librbd1 liburcu6 MACSio MACSio-mpich MACSio-openmpi3 mercury 
mpi4py-common mpi4py-tests mpich openmpi2 openmpi2-libs perl-common-sense perl-JSON perl-JSON-XS 
perl-Types-Serialiser protobuf-c python2-configshell-fb python2-mpi4py-mpich python2-tabulate python2-urwid 
python-curses romio-tests spdk spdk-tools testmpio
```

Notice we have `hdf5-vol-daos-mpich`, whereas for mpifileutils we have `libmfu0-mpich`.
I wonder if maybe it has something to do with the `%files -n libmfu0-mpich`, so I removed the provides for the libmfu variants and and testing this theory on my PR.

2020-11-06 14:19 UTC, daltonbohning commented
With this change, `dcp` is being found, but now the shared library `libmpi.so.20` is not.
This is a step closer, but not complete.

2020-11-07 04:08 UTC, daltonbohning commented
I tried removing the `libmfu` variants entirely, but now `dcp` is not found again.

2020-11-09 19:28 UTC, brianjmurrell requested changes
This is all wrong.  It violates SUSE's library packaging standards, which are quite different from RedHat's to be sure, which is why there are extra `lib*` packages for Leap 15.

2020-11-09 19:31 UTC, daltonbohning commented
I was really just making wild guesses here, as I'm not familiar with SUSE at all

2020-11-09 19:34 UTC, brianjmurrell commented
> I was really just making wild guesses here, as I'm not familiar with SUSE at all

Yeah, fair enough.  It just wasn't the right guess in this case.  The real solution here is to figure out _why_ `dcp` isn't being found and the most likely cause lies in the environment, given that it's an MPI binary and the environment has to configured properly with `module` before MPI binaries will be found and their libraries found.

2020-11-10 23:53 UTC, daltonbohning commented
@brianjmurrell
This fixes the issue where `dcp` itself was not being installed at all, by moving the `Provides:` from the `libmfu0-*` packages to the `<mpi>*` packages as we discussed.

Locally, it seems that `dcp` is up and running on my local leap15 node.

2020-11-16 15:23 UTC, daltonbohning commented
@brianjmurrell Does this current state look good to you?

2020-11-16 17:17 UTC, brianjmurrell approved these changes

2020-11-16 17:46 UTC, daltonbohning commented
@brianjmurrell Thanks for abundance of help! 
I don't have merge permissions myself (probably shouldn't) and there doesn't appear to be a "package-gatekeeper". Maybe @JohnMalmberg ?

2020-11-16 18:58 UTC, brianjmurrell commented
> @brianjmurrell Thanks for abundance of help!

NP.  Happy to help.

> I don't have merge permissions myself (probably shouldn't) and there doesn't appear to be a "package-gatekeeper". Maybe @JohnMalmberg ?

@daos-stack/release-engineering 

But I will just go ahead and land it since you seem to be ready for that.

2020-11-16 18:58 UTC, merged

2020-11-16 19:01 UTC, daltonbohning commented
> @daos-stack/release-engineering
> 
> But I will just go ahead and land it since you seem to be ready for that.

Ah! Thanks again! :)