SRE-2513: New LICENSE file as expected by OpenSSF Scorecard
daos-stack/mpifileutils-pkg pull request #39
Opened 2024-10-01 12:19 UTC by osalyk

Doc-only: true

2024-10-01 16:33 UTC, grom72 approved these changes

2024-10-04 08:30 UTC, janekmi requested changes

2024-10-04 08:30 UTC, janekmi commented on Makefile
> +# Copyright (C) 2019-2024 Intel Corporation
```suggestion
# Copyright (c) 2020-2024 Intel Corporation
```

2024-10-04 09:03 UTC, osalyk commented on Makefile
> +# Copyright (C) 2019-2024 Intel Corporation
Done.

2024-10-04 10:04 UTC, grom72 approved these changes

2024-10-04 10:51 UTC, janekmi approved these changes

2024-10-07 18:07 UTC, merged